#!/usr/bin/env python3
"""
Generate Niubash completion TOML from WinuxCmd help output.

The generator has two layers:
  1. Core WinuxCmd commands discovered from `winuxcmd.exe --help`.
  2. Optional installed tools in the same WinuxCmd root via `--include-installed`.

Generated TOML is intentionally static. Runtime completion should stay reserved
for values that are truly environment-dependent.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = ROOT.parent / "unixwin-oh-my-niu" / "completions"

GENERATED_HEADER = "# Generated by scripts/generate-winuxcmd-completions.py; do not edit by hand."
SAFE_COMMAND_RE = re.compile(r"^[A-Za-z0-9_.+-]+$")
INVENTORY_RE = re.compile(r"^\s{2,}([A-Za-z0-9_.+-]+)\s{2,}(.+?)\s*$")
OPTION_START_RE = re.compile(r"^\s{2,}(-[A-Za-z0-9?]|--[A-Za-z0-9][A-Za-z0-9_.-]*|-\d)")
OPTION_LINE_RE = re.compile(r"^\s{2,}(.+?)(?:\s{2,}(.+))?$")
LONG_OPTION_RE = re.compile(r"^(--[A-Za-z0-9][A-Za-z0-9_.-]*)(.*)$")
SHORT_OPTION_RE = re.compile(r"^(-[A-Za-z0-9?][A-Za-z0-9_.-]*|-\d+)(.*)$")
VALUE_HINT_RE = re.compile(r"(?:^|[\s=\[<])(ARG|ARGS|NUM|NUMBER|FILE|FILES|DIR|DIRECTORY|PATH|PATTERN|WHEN|WORD|MODE|SIZE|TYPE|NAME|COMMAND|FORMAT|STYLE|COLOR|KEY|VALUE|N)(?:\]|\>|$|\s)", re.I)
POSSIBLE_VALUES_RE = re.compile(r"\[possible values?:\s*([^\]]+)\]", re.I)
QUOTED_VALUES_RE = re.compile(r"'([A-Za-z0-9_.+-]+)'")


STATIC_VALUES: dict[tuple[str, str], list[str]] = {
    ("find", "-type"): ["f", "d", "l"],
    ("find", "-xtype"): ["f", "d", "l"],
    ("grep", "--color"): ["always", "auto", "never"],
    ("grep", "--colour"): ["always", "auto", "never"],
    ("ls", "--color"): ["always", "auto", "never"],
    ("ls", "--sort"): ["none", "size", "time", "version", "extension"],
    ("ls", "--format"): [
        "across",
        "commas",
        "horizontal",
        "long",
        "single-column",
        "verbose",
        "vertical",
    ],
    ("ls", "--time"): ["atime", "access", "use", "ctime", "status"],
    ("rm", "--interactive"): ["never", "once", "always"],
    ("touch", "--time"): ["access", "atime", "use", "modify", "mtime"],
}

PATH_VALUE_NAMES = {
    "--directory",
    "--file",
    "--files0-from",
    "--reference",
    "--target-directory",
    "--root",
    "--work-tree",
    "--git-dir",
}

PATH_VALUE_WORDS = (
    "file",
    "files",
    "dir",
    "directory",
    "path",
    "reference",
    "root",
)


@dataclass
class Flag:
    short: str | None = None
    long: str | None = None
    description: str | None = None
    takes_value: bool = False
    values: list[str] = field(default_factory=list)
    values_from_path: bool = False


@dataclass
class CommandDef:
    command: str
    description: str | None = None
    flags: list[Flag] = field(default_factory=list)


def run_capture(args: list[str], timeout: float) -> tuple[int | None, str]:
    try:
        proc = subprocess.run(
            args,
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
        return proc.returncode, proc.stdout.replace("\r\n", "\n")
    except subprocess.TimeoutExpired as exc:
        output = ""
        if exc.stdout:
            output += exc.stdout if isinstance(exc.stdout, str) else exc.stdout.decode("utf-8", "replace")
        if exc.stderr:
            output += exc.stderr if isinstance(exc.stderr, str) else exc.stderr.decode("utf-8", "replace")
        return None, output
    except OSError as exc:
        return None, str(exc)


def locate_winuxcmd(explicit: str | None) -> Path:
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit))
    if os.environ.get("WINUXCMD_PATH"):
        candidates.append(Path(os.environ["WINUXCMD_PATH"]))

    path_hit = shutil.which("winuxcmd.exe") or shutil.which("winuxcmd")
    if path_hit:
        candidates.append(Path(path_hit))

    for candidate in candidates:
        if candidate.is_dir():
            candidate = candidate / "winuxcmd.exe"
        if candidate.is_file():
            return candidate

    raise SystemExit("winuxcmd.exe not found; pass --winuxcmd or set WINUXCMD_PATH")


def discover_core_commands(winuxcmd: Path, timeout: float) -> dict[str, str]:
    _, help_text = run_capture([str(winuxcmd), "--help"], timeout)
    commands: dict[str, str] = {}
    in_commands = False

    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped == "Available Commands:":
            in_commands = True
            continue
        if not in_commands:
            continue
        if not stripped:
            continue
        match = INVENTORY_RE.match(line)
        if not match:
            continue
        command, summary = match.groups()
        if SAFE_COMMAND_RE.match(command):
            commands.setdefault(command, summary.strip())

    return commands


def discover_installed_commands(winuxcmd: Path) -> dict[str, str]:
    root = winuxcmd.parent
    commands: dict[str, str] = {}
    for exe in sorted(root.glob("*.exe")):
        name = exe.stem
        if name.lower() == "winuxcmd" or not SAFE_COMMAND_RE.match(name):
            continue
        commands[name] = f"{name} command installed in the WinuxCmd root"
    return commands


def command_help(
    winuxcmd: Path,
    command: str,
    timeout: float,
    installed: bool,
    help_arg: str = "--help",
) -> str:
    if installed:
        exe = winuxcmd.parent / f"{command}.exe"
        if exe.is_file():
            _, output = run_capture([str(exe), help_arg], timeout)
            return output
    _, output = run_capture([str(winuxcmd), command, help_arg], timeout)
    return output


def parse_description(help_text: str, fallback: str | None) -> str | None:
    lines = help_text.splitlines()
    desc: list[str] = []
    seen_usage = False

    for line in lines:
        stripped = line.strip()
        lower = stripped.lower()
        if lower.startswith("usage:") or lower == "usage:":
            seen_usage = True
            continue
        if not seen_usage:
            continue
        if is_option_section_header(stripped) or lower in {"commands:", "arguments:", "positional arguments:", "exit status:"}:
            break
        if not stripped:
            if desc:
                break
            continue
        if stripped.startswith("Usage:"):
            continue
        desc.append(stripped)

    description = " ".join(desc).strip()
    return description or fallback


def is_option_section_header(stripped: str) -> bool:
    lower = stripped.lower()
    return lower in {"options:", "flags:", "command options:", "global options:"} or lower.endswith(" options:")


def parse_flags(command: str, help_text: str) -> list[Flag]:
    blocks: list[tuple[str, str]] = []
    in_options = False
    current_spec: str | None = None
    current_desc: list[str] = []

    for line in help_text.splitlines():
        stripped = line.strip()
        if is_option_section_header(stripped):
            in_options = True
            flush_block(blocks, current_spec, current_desc)
            current_spec = None
            current_desc = []
            continue
        if not in_options:
            continue
        if not stripped:
            continue
        if stripped.endswith(":") and not OPTION_START_RE.match(line):
            # fzf-style subgroups inside the options section; keep parsing.
            continue
        if stripped.lower() in {"exit status:", "examples:", "available commands:", "commands:", "arguments:"}:
            break

        if OPTION_START_RE.match(line):
            flush_block(blocks, current_spec, current_desc)
            match = OPTION_LINE_RE.match(line)
            if not match:
                current_spec = None
                current_desc = []
                continue
            current_spec = match.group(1).strip()
            current_desc = [match.group(2).strip()] if match.group(2) else []
        elif current_spec is not None:
            current_desc.append(stripped)

    flush_block(blocks, current_spec, current_desc)

    flags: list[Flag] = []
    seen: set[tuple[str | None, str | None]] = set()
    for spec, description in blocks:
        flag = parse_flag_spec(command, spec, description)
        if flag is None:
            continue
        key = (flag.short, flag.long)
        if key in seen:
            continue
        seen.add(key)
        flags.append(flag)
    return flags


def flush_block(blocks: list[tuple[str, str]], spec: str | None, desc: list[str]) -> None:
    if not spec:
        return
    description = " ".join(part.strip() for part in desc if part.strip()).strip()
    blocks.append((spec, description))


def parse_flag_spec(command: str, spec: str, description: str) -> Flag | None:
    pieces = [piece.strip() for piece in spec.split(",")]
    short: str | None = None
    long: str | None = None
    takes_value = False

    for piece in pieces:
        if not piece:
            continue
        parsed, trailing, kind = normalize_option(piece)
        if parsed is None:
            continue
        if kind == "long":
            long = parsed
        elif kind == "short":
            short = parsed
        if trailing and looks_value_hint(trailing):
            takes_value = True
        if "[=" in piece or "=" in piece:
            takes_value = True

    if short is None and long is None:
        return None

    flag = Flag(short=short, long=long, description=description or None, takes_value=takes_value)
    assign_value_source(command, flag)
    return flag


def normalize_option(piece: str) -> tuple[str | None, str, str | None]:
    piece = piece.strip()
    if piece.startswith("+"):
        return None, "", None

    long_match = LONG_OPTION_RE.match(piece)
    if long_match:
        option = long_match.group(1)
        if option.endswith("..."):
            option = option[:-3]
        trailing = long_match.group(2).strip()
        return option, trailing, "long"

    short_match = SHORT_OPTION_RE.match(piece)
    if short_match:
        option = short_match.group(1)
        trailing = short_match.group(2).strip()
        return option, trailing, "short"

    return None, "", None


def looks_value_hint(trailing: str) -> bool:
    return bool(
        VALUE_HINT_RE.search(trailing)
        or re.search(r"<[^>]+>", trailing)
        or re.search(r"\[[A-Z0-9_ -]+\]", trailing)
    )


def assign_value_source(command: str, flag: Flag) -> None:
    if not flag.takes_value:
        return

    for name in [flag.long, flag.short]:
        if name and (command, name) in STATIC_VALUES:
            flag.values = STATIC_VALUES[(command, name)]
            return

    possible = extract_possible_values(flag.description or "")
    if possible:
        flag.values = possible
        return

    names = [name for name in [flag.long, flag.short] if name]
    description = (flag.description or "").lower()
    if any(name in PATH_VALUE_NAMES for name in names) or any(word in description for word in PATH_VALUE_WORDS):
        flag.values_from_path = True


def extract_possible_values(description: str) -> list[str]:
    match = POSSIBLE_VALUES_RE.search(description)
    if match:
        raw = match.group(1)
        values = [part.strip(" `,.;") for part in re.split(r"[,|]", raw)]
        return [value for value in values if value and " " not in value]

    quoted = QUOTED_VALUES_RE.findall(description)
    if 2 <= len(quoted) <= 8:
        return quoted

    return []


def toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_command(defn: CommandDef) -> str:
    lines = [GENERATED_HEADER, f'command = "{toml_escape(defn.command)}"']
    if defn.description:
        lines.append(f'description = "{toml_escape(defn.description)}"')

    for flag in defn.flags:
        lines.append("")
        lines.append("[[flags]]")
        if flag.short:
            lines.append(f'short = "{toml_escape(flag.short)}"')
        if flag.long:
            lines.append(f'long = "{toml_escape(flag.long)}"')
        if flag.description:
            lines.append(f'description = "{toml_escape(flag.description)}"')
        if flag.takes_value:
            lines.append("takes_value = true")
        if flag.values:
            rendered = ", ".join(f'"{toml_escape(value)}"' for value in flag.values)
            lines.append(f"values = [{rendered}]")
        elif flag.values_from_path:
            lines.append('values_from = "path"')

    lines.append("")
    return "\n".join(lines)


def generated_filename(command: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.+-]+", "_", command).strip("._")
    return f"{safe or 'command'}.toml"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--winuxcmd", help="Path to winuxcmd.exe or its containing directory")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--timeout", type=float, default=2.5)
    parser.add_argument(
        "--include-installed",
        action="store_true",
        help="Also parse installed .exe tools in the WinuxCmd root, including WPM packages",
    )
    parser.add_argument(
        "--commands",
        help="Comma-separated command allowlist; useful for focused regeneration",
    )
    args = parser.parse_args()

    winuxcmd = locate_winuxcmd(args.winuxcmd)
    commands = discover_core_commands(winuxcmd, args.timeout)
    installed_commands: set[str] = set()

    if args.include_installed:
        installed = discover_installed_commands(winuxcmd)
        installed_commands = set(installed) - set(commands)
        commands.update(installed)

    if args.commands:
        allowed = {item.strip() for item in args.commands.split(",") if item.strip()}
        commands = {name: summary for name, summary in commands.items() if name in allowed}

    if not commands:
        raise SystemExit("no commands discovered")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    generated = 0
    skipped = 0
    for command, fallback in sorted(commands.items()):
        help_text = command_help(
            winuxcmd,
            command,
            args.timeout,
            installed=command in installed_commands,
        )
        flags = parse_flags(command, help_text)
        if not flags:
            short_help = command_help(
                winuxcmd,
                command,
                args.timeout,
                installed=command in installed_commands,
                help_arg="-h",
            )
            short_flags = parse_flags(command, short_help)
            if short_flags:
                help_text = short_help
                flags = short_flags
        if not flags and not help_text.strip():
            skipped += 1
            continue
        defn = CommandDef(
            command=command,
            description=parse_description(help_text, fallback),
            flags=flags,
        )
        (args.out_dir / generated_filename(command)).write_text(
            render_command(defn),
            encoding="utf-8",
            newline="\n",
        )
        generated += 1

    print(
        f"generated {generated} completion definitions from {winuxcmd}; "
        f"skipped {skipped}; output {args.out_dir}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
